# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Bio
    identifier: c2a35780
    url: /
    weight: 10
  - name: Skills
    identifier: 0fc38034
    url: /#skills
    weight: 20
  - name: Projects
    identifier: cca0e8b2
    url: /#projects
    weight: 30
